name: CI
on:
  push:
    branches: [ master, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run validation
        run: |
          python scripts/compute_attestation.py > computed.sha256
          mkdir -p artifacts
          mv computed.sha256 artifacts/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: attestation
          path: artifacts/computed.sha256
